name: Update Profiles

on:
  push:
    paths:
      - app/data/profiles.json

jobs:
  push_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }} # Verwende den PAT als Authentifizierung
      - name: Configure Git
        run: |
          git config --global user.name "Question86"
          git config --global user.email "Question86@protonmail.com"
      - name: Commit and Push Changes
        run: |
          git add app/data/profiles.json
          git commit -m "Auto-update profiles.json" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/Question86/Ray_pub.git
